### ISSUE TITLE
[Feature] Custom Wads & Mods Support

### ISSUE THREAD

**Issue by IDDQD1337** [vs-shirokii/gzdoom-rt#19]
### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Other

### Is your feature request related to a problem? Please describe.

I don't really like (with rare exceptions) vanilla gameplay and I think it's worth adding the ability to install some gameplay mods and custom wads (megawads)

**Comment by tokariu** [comment]
correct me if I'm wrong, but isn't that exactly what [1.0.2a] Mod Support does (see download section 
gzdoom-rt-modcompatibility-1.zip):

> Doom II: Ray Traced might be compatible with existing GZDoom mods, but expect instability, visual artifacts and performance issues. So, to run custom .wad / .pk3 / other mods:
> 
>     Download gzdoom-rt-modcompatibility-1.zip
>     Unpack it into your Doom II: Ray Traced folder
>     Drag-and-drop your mod file (e.g. [brutalv21.pk3](https://www.moddb.com/mods/brutal-doom/downloads/brutal-doom-v21-beta)) onto gzdoom-mod-launcher.bat to launch
