### ISSUE TITLE
[Feature] reduce blood fluid bubbles

### ISSUE THREAD

**Issue by Hexaae** [vs-shirokii/gzdoom-rt#20]
### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

Is there a way to reduce enemies blood blobs size? They seem too big and abundant, proportionally speaking they look like magnified...

**Comment by tokariu** [comment]
off/normal/groovy are the options I don't think it's possible to change the fluid system otherwise.

**Comment by vs-shirokii** [comment]
In console (press \` ):

1. Type `rt_fluid_pradius 0.07` to reduce particle radius. Default 0.1
2. Then need to restart fluid by typing:
    1. `rt_fluid 0`
    1. and after that `rt_fluid 1`

**Comment by Hexaae** [comment]
Thank you! 0.025 is good for me... 😊 and it gets stored in the prefs on next launch, great!

**Comment by TheNametag** [comment]
Can this be added as a slider or option in future versions to make it easier to adjust?  I personally have found that 0.04 works for me, and each person would likely prefer a different amount that suits them.
