### ISSUE TITLE
[BUG] Does not launch

### ISSUE THREAD

**Issue by OP-R8R** [vs-shirokii/gzdoom-rt#29]
### GZDoom version

GZdoom 4.11.9999.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Win11 pro with latest updates and latest driver versions.

### Relevant hardware info

i7 8700k - RTX2070S

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Does not seem to work. I get to the screen to select the game... after that a blue screen with the last line being "RTinit: Ray tracing initialization processs." and thats it. Task manager shows a fatal error on the process. "Fatal Error - GZDoom g4.11pre-712-ge618865ce 64-bit"

### Steps to reproduce the behaviour.

see error description

### Your configuration

```ini
have not edited any config files since it never ran
```

### Provide a Log

no error log produced (at least to my knowledge)

**Comment by vs-shirokii** [comment]
Wonder what was the reason

**Comment by OP-R8R** [comment]
An access restriction in windows. Not a bug with the mod. Just windows doing stupid windows stuff sometimes. Sry.

**Comment by miguelgm** [comment]
> An access restriction in windows. Not a bug with the mod. Just windows doing stupid windows stuff sometimes. Sry.

how did you solved it? I'm getting the same error :-/
