### ISSUE TITLE
[HELP] Custom music WAD not working

### ISSUE THREAD

**Issue by BrochachoTheBro** [vs-shirokii/gzdoom-rt#6]
I made a little music pack that replaces the MIDI tracks from Doom and Doom II with their Andrew Hulshult counterparts from the recent rerelease, and it works just fine in standard GZDoom. However, when I load the wad in GZDoomRT, none of the music is replaced; it just sticks to the default MIDI tracks. Is there a specific way custom music needs to be applied to GZDoomRT? Mainly looking for a solution for this because Sultim's original PrBoom+RT had an option for Andrew Hulshult's Doom 1 score and would like parity on that front.

**Comment by Aelussa** [comment]
It seems like this mod doesn't use the MIDI tracks from the doom2.wad for some reason, instead it has the music in .ogg files in the mod's folder. If you go to "/rt/wad/filter/doom.id.doom2/MUSIC/", you can replace the .ogg files there to use Andrew Hulshult's music with this mod.

**Comment by BrochachoTheBro** [comment]
> It seems like this mod doesn't use the MIDI tracks from the doom2.wad for some reason, instead it has the music in .ogg files in the mod's folder. If you go to "/rt/wad/filter/doom.id.doom2/MUSIC/", you can replace the .ogg files there to use Andrew Hulshult's music with this mod.

Works, cool ty
